function [Prob] = getSequenceProb(CompleteSequence)

A = length(strfind(CompleteSequence,'A'));
B = length(strfind(CompleteSequence,'B'));
C = length(strfind(CompleteSequence,'C'));
D = length(strfind(CompleteSequence,'D'));
E = length(strfind(CompleteSequence,'E'));
F = length(strfind(CompleteSequence,'F'));
G = length(strfind(CompleteSequence,'G'));
H = length(strfind(CompleteSequence,'H'));
I = length(strfind(CompleteSequence,'I'));
J = length(strfind(CompleteSequence,'J'));
K = length(strfind(CompleteSequence,'K'));
L = length(strfind(CompleteSequence,'L'));
M = length(strfind(CompleteSequence,'M'));
N = length(strfind(CompleteSequence,'N'));
O = length(strfind(CompleteSequence,'O'));
P = length(strfind(CompleteSequence,'P'));
Q = length(strfind(CompleteSequence,'Q'));
R = length(strfind(CompleteSequence,'R'));
S = length(strfind(CompleteSequence,'S'));
T = length(strfind(CompleteSequence,'T'));
U = length(strfind(CompleteSequence,'U'));
V = length(strfind(CompleteSequence,'V'));
W = length(strfind(CompleteSequence,'W'));
X = length(strfind(CompleteSequence,'X'));
Y = length(strfind(CompleteSequence,'Y'));
Z = length(strfind(CompleteSequence,'Z'));

Total = numel(CompleteSequence);

ProbA = A/Total;
ProbB = B/Total;
ProbC = C/Total;
ProbD = D/Total;
ProbE = E/Total;
ProbF = F/Total;
ProbG = G/Total;
ProbH = H/Total;
ProbI = I/Total;
ProbJ = J/Total;
ProbK = K/Total;
ProbL = L/Total;
ProbM = M/Total;
ProbN = N/Total;
ProbO = O/Total;
ProbP = P/Total;
ProbQ = Q/Total;
ProbR = R/Total;
ProbS = S/Total;
ProbT = T/Total;
ProbU = U/Total;
ProbV = V/Total;
ProbW = W/Total;
ProbX = X/Total;
ProbY = Y/Total;
ProbZ = Z/Total;

Prob = [
    ProbA;
    ProbB;
    ProbC;
    ProbD;
    ProbE;
    ProbF;
    ProbG;
    ProbH;
    ProbI;
    ProbJ;
    ProbK;
    ProbL;
    ProbM;
    ProbN;
    ProbO;
    ProbP;
    ProbQ;
    ProbR;
    ProbS;
    ProbT;
    ProbU;
    ProbV;
    ProbW;
    ProbX;
    ProbY;
    ProbZ; ];